// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtlexgrimvztsdfevwvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0bGV4Z3JpbXZ6dHNkZmV2d3ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzg1NjIsImV4cCI6MjA3Mzg1NDU2Mn0.Tcv5CGMsu20t3C-my7bC41sBR4t41K3YDOsgIfzoaQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});